@url_base = http://localhost:5125/api/usuario

### Cadastrar usuário
POST {{url_base}}/cadastrar
Content-Type: application/json
 

{
    "email" : "Teste1",
    "senha" : "1234"
}

### Login
POST {{url_base}}/login
Content-Type: application/json

{
    "email" : "Teste2",
    "senha" : "1234"
}

### Listar usuários
GET {{url_base}}/listar